spring:
  application:
    name: backend

  datasource:
    url: jdbc:mysql://localhost:3306/fl_backend?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

jwt:
  secret: averylongsecretkeywhichisatleast256bitlongforhmacsha256algorithm1234567890
  expiration: 900000 # 15 minutes
