CREATE TABLE hospital (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    contact_email VARCHAR(255) NOT NULL
);

CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL,
    hospital_id BIGINT,
    FOREIGN KEY (hospital_id) REFERENCES hospital(id)
);

CREATE TABLE training_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status VARCHAR(50) NOT NULL,
    total_rounds INT NOT NULL,
    idempotency_key VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE federated_round (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    round_number INT NOT NULL,
    global_accuracy DOUBLE PRECISION,
    global_loss DOUBLE PRECISION,
    checkpoint_path VARCHAR(500),
    FOREIGN KEY (session_id) REFERENCES training_session(id)
);

CREATE TABLE client_round_status (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    round_id BIGINT NOT NULL,
    hospital_id BIGINT NOT NULL,
    local_accuracy DOUBLE PRECISION,
    local_loss DOUBLE PRECISION,
    sample_count INT,
    FOREIGN KEY (round_id) REFERENCES federated_round(id),
    FOREIGN KEY (hospital_id) REFERENCES hospital(id)
);

CREATE TABLE model_version (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    round_number INT NOT NULL,
    model_path VARCHAR(500),
    accuracy DOUBLE PRECISION,
    precision_score DOUBLE PRECISION,
    recall DOUBLE PRECISION,
    f1 DOUBLE PRECISION,
    is_active BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (session_id) REFERENCES training_session(id)
);

CREATE TABLE prediction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hospital_id BIGINT,
    model_version_id BIGINT,
    patient_features VARCHAR(2000),
    result VARCHAR(255),
    FOREIGN KEY (hospital_id) REFERENCES hospital(id),
    FOREIGN KEY (model_version_id) REFERENCES model_version(id)
);

CREATE TABLE comparison_result (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    approach_type VARCHAR(50),
    accuracy DOUBLE PRECISION,
    f1_score DOUBLE PRECISION,
    training_time_sec BIGINT,
    FOREIGN KEY (session_id) REFERENCES training_session(id)
);

CREATE TABLE audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    action VARCHAR(255) NOT NULL,
    resource_id VARCHAR(255),
    ip_address VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES app_user(id)
);
